# This Makefile will run the awk script called 'program.awk' along with the CSV file and generate a report on the CSV data

awk: program.awk
        awk -f program.awk ~/awk-and-makefile/data/oscar_age_male.csv
